version: '3.8'
services:
  nginx-proxy:
    image: nginx:1.25.3-alpine
    volumes:
      - ./nginxProxy/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    depends_on:
      - maps-service
    networks:
      - app
  maps-service:
    build: ./mapService
    ports:
      - "3001:3001"
    volumes:
      - ./mapService:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/mapService
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db
    networks:
      - app

networks:
  app:
    driver: bridge

volumes:
  mongodb:
    driver: local